modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL="https://github.com/JuiceyBeans/Chickens-Hatch-Now/updates.json"
displayURL="https://modrinth.com/mod/chickens-hatch-now/"
logoFile="icon.png"
credits="The_Only_Rosalyn for wanting this mod made, GTCEu Modern devs for helping with code"
authors = "${mod_authors}"
displayTest="MATCH_VERSION"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
